# Usage: cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P EmbedBinary.cmake
# Emits `extern const unsigned char SYMBOL[]; extern const size_t SYMBOL_size;`
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _len)
math(EXPR _bytes "${_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")
file(WRITE "${OUTPUT}" "// Generated by EmbedBinary.cmake from ${INPUT}\n#include <cstddef>\nextern const unsigned char ${SYMBOL}[] = {${_body}};\nextern const size_t ${SYMBOL}_size = ${_bytes};\n")
